/**
 * Code is auto-generated by Application Logic, DO NOT EDIT.
 * @version(2.0)
 */
const LCAPApplicationService = require('@sap/low-code-event-handler');
const products_Logic = require('./code/products-logic');
const suppliers_Logic = require('./code/suppliers-logic');
const categories_Logic = require('./code/categories-logic');
const orderdetails_Logic = require('./code/orderdetails-logic');

class NorthwindSrv extends LCAPApplicationService {
    async init() {

        this.on(['CREATE', 'DELETE', 'READ', 'UPDATE'], 'Products', async (request, next) => {
            await products_Logic(request);
            return next();
        });

        this.on(['CREATE', 'DELETE', 'READ', 'UPDATE'], 'Suppliers', async (request, next) => {
            await suppliers_Logic(request);
            return next();
        });

        this.on(['CREATE', 'DELETE', 'READ', 'UPDATE'], 'Categories', async (request, next) => {
            await categories_Logic(request);
            return next();
        });

        this.on(['CREATE', 'DELETE', 'READ', 'UPDATE'], 'OrderDetails', async (request, next) => {
            await orderdetails_Logic(request);
            return next();
        });

        return super.init();
    }
}


module.exports = {
    NorthwindSrv
};